### ISSUE TITLE
4.2 ระบบ Spawn Zombie

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#11]

**Comment by TIT4nnnx** [comment]
Spawn Zombie ยังไม่ Success

**Comment by Tiggers123** [comment]
https://scratch.mit.edu/projects/731405551 ตอนนี้เพื่มไปแค่ซอมบี้นักวิ่งนะกับการเกิดซอมบี้รอบทิศทางส่วนซอมบี้โดน3นัดตายจะเพิ่มมาในอนาคตนะ
