### ISSUE TITLE
4.4 ระบบ Score counting

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#13]

**Comment by Waphyoo** [comment]
shout skill v.1
health system v.1
end game v.1
score counting v.1
shooting v.2
https://scratch.mit.edu/projects/729924762

**Comment by Waphyoo** [comment]
shout skill v.1
health system v.1
end game v.2 (show score on game over screen)
score counting v.2(show leaderboard with conditional sequence )
shooting v.2 

https://scratch.mit.edu/projects/729924762

**Comment by Waphyoo** [comment]
ระบบ เหลือเก็บกระสุน กับ อัลติ ป่ะ

**Comment by TIT4nnnx** [comment]
> ระบบ เหลือเก็บกระสุน กับ อัลติ ป่ะ

ช่ายย
