### ISSUE TITLE
4.6 ระบบ Skill

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#15]

**Comment by Waphyoo** [comment]
shout skill v.1

https://scratch.mit.edu/projects/729894131/editor

**Comment by Waphyoo** [comment]
shout skill v.1
health system v.1
end game v.1

https://scratch.mit.edu/projects/729907839

**Comment by Waphyoo** [comment]
ultimate v.1
https://scratch.mit.edu/projects/731316415

**Comment by Waphyoo** [comment]
ultimate v.2 (no cooldown)

https://scratch.mit.edu/projects/731739033

**Comment by Waphyoo** [comment]
ultimate v.2.1 (has cooldown counting)

https://scratch.mit.edu/projects/731739033
