### ISSUE TITLE
📍📍 ทรัพยากร art work 📍📍

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#16]

**Comment by ApichayaUWU** [comment]
Candy Bullet
![Ingame 3](https://user-images.githubusercontent.com/110961569/189327810-b44a4588-06ca-40a1-a187-3a790ea16114.png)

**Comment by ApichayaUWU** [comment]
โมเดล ลุงร็อบ
![uncle rob](https://user-images.githubusercontent.com/110961569/189328280-3a0e811b-75f8-46a9-ab84-417cc77c8503.png)
พ๊อยเตอร์
![Pointer](https://user-images.githubusercontent.com/110961569/189328284-11d2efec-69a1-4d8e-a5ee-fa32810280a3.png)

**Comment by ApichayaUWU** [comment]
game over pixel art
![Game_Over 2](https://user-images.githubusercontent.com/110961569/189514120-cfd3f6ec-5b3e-4878-8058-f29381e2bd27.png)

**Comment by ApichayaUWU** [comment]
Uncle Rob in pixel art
![Uncle_Rob_Pixel 3](https://user-images.githubusercontent.com/110961569/189515903-a6753e69-8cb5-4db8-b5e2-064b7fa9376f.png)

**Comment by ApichayaUWU** [comment]
candy bullet and pointer in pixel art
![Candy_Pixel](https://user-images.githubusercontent.com/110961569/189517033-a89d02f9-c30b-4355-b2b3-63e8442c9f3c.png)
![Pointer_Pixel](https://user-images.githubusercontent.com/110961569/189517036-47f7b3f9-910b-4375-97b6-15380a8709d2.png)

**Comment by ApichayaUWU** [comment]
Normal zombie
![Normal_Zombie_Pixel](https://user-images.githubusercontent.com/110961569/189518756-e93b7c88-cc0e-4818-a002-fda5529e3db4.gif)

**Comment by ApichayaUWU** [comment]
HP gauge
![Hp_Gauge](https://user-images.githubusercontent.com/110961569/189521467-7c4c3d67-b030-4fe5-ad51-3ebad4e3b762.gif)

**Comment by ApichayaUWU** [comment]
kid pixel
![Normal_Kid_Pixel](https://user-images.githubusercontent.com/110961569/189688436-3810bcd4-de2e-4c29-8d30-d0ac897e35cd.png)

**Comment by ApichayaUWU** [comment]
Shogun shooting animation
![Shotgun_Pixel](https://user-images.githubusercontent.com/110961569/189697212-41e67d86-af85-4eb9-a75c-df684f31dfe8.gif)


[SAMPLE] shooting animation with uncle rob model
![Shotgun:wRob_Pixel](https://user-images.githubusercontent.com/110961569/189698591-2c2324c5-af35-4ef5-b1e9-e5eadf5eecd1.gif)

**Comment by ApichayaUWU** [comment]
Reloading shotgun animation
![Reload_Shotgun_Pixel](https://user-images.githubusercontent.com/110961569/189705378-fd9f1493-da50-444a-9bfc-0f8392ff1a16.gif)

**Comment by ApichayaUWU** [comment]
HP ITEM 
![Hp_Item_Pixel](https://user-images.githubusercontent.com/110961569/189875279-9350db9f-8211-4fc6-8610-33ce7747275f.png)

**Comment by ApichayaUWU** [comment]
ซอมบี้นักวิ่ง เราตั้งค่าอนิเมชั่นปกติไว้ที่14fpsนะ
![Athletics_Zombie_Pixel](https://user-images.githubusercontent.com/110961569/190037190-e00f9993-71c9-493e-81e8-b1a13aefe859.gif)

**Comment by ApichayaUWU** [comment]
UI leaderboard //ยังไม่ต้องเอาไปใส่นะ โค้ดระบบเบื้อหลังUIเด่ะเราจะอัพให้อีกทีตอนสมบูรณ์แล้ว
[preview]
![Score_board 2](https://user-images.githubusercontent.com/110961569/190587377-f278f1f1-e94c-43a2-906d-04c1d46d7bc8.png)

[element]
![Score_board](https://user-images.githubusercontent.com/110961569/190587779-43b7d598-5689-4076-bd3b-3f2da4b5258e.png)
![Name](https://user-images.githubusercontent.com/110961569/190587809-ac2707bf-884f-48f9-addd-636a0dbff9d1.png)
![Start](https://user-images.githubusercontent.com/110961569/190588731-735d47b7-b40a-433b-b882-e236785a84ea.png)
![Text](https://user-images.githubusercontent.com/110961569/190587923-afb062a7-a4de-4fab-9ab5-73f74e76f335.gif)
![glitching](https://user-images.githubusercontent.com/110961569/190889934-ab07a9c6-0e0e-4707-899b-b73f280b85fd.gif)

**Comment by ApichayaUWU** [comment]
shubby zombie
![Shubby_Zombie_Pixel](https://user-images.githubusercontent.com/110961569/190888865-b099f48a-9dcd-427f-aae0-007ecc1886fc.gif)

**Comment by ApichayaUWU** [comment]
ultimate

![Ultimate](https://user-images.githubusercontent.com/110961569/190889216-3f76babe-a4ef-41ef-a4db-579c773768a9.gif)
![Ultimate 2](https://user-images.githubusercontent.com/110961569/190889240-c2631802-ff73-42ec-987a-4262eac59f1f.gif)

**Comment by ApichayaUWU** [comment]
Sample skill SHOUT!
![sample_Skill](https://user-images.githubusercontent.com/110961569/191191342-6d4f78a7-4e97-47f7-a23f-4b68076f45f5.gif)

element
![Skill_2](https://user-images.githubusercontent.com/110961569/191191130-054bec19-7828-4d00-9bff-a0d84b4f8f37.gif)
![Skill](https://user-images.githubusercontent.com/110961569/191191136-a325a7b3-4ed7-4117-8fc0-6cd143959e85.gif)

**Comment by ApichayaUWU** [comment]
Hubby kid pixel
![Shubby-Kid-Pixel](https://user-images.githubusercontent.com/110961569/191203395-00a30304-4f86-42fb-a7d3-1c05f8b0c61f.png)

**Comment by ApichayaUWU** [comment]
Skill  and ultimate Icon
![Skill_Icon](https://user-images.githubusercontent.com/110961569/191205003-31eaa814-cbea-4c94-b353-96154eceabd5.gif)
![Ultimate_Icon](https://user-images.githubusercontent.com/110961569/191205015-a8ddf396-89b4-493e-9b73-72000256e95b.gif)

**Comment by Tiggers123** [comment]
![74854f1bec2f71a131c6e3f250774d8a](https://user-images.githubusercontent.com/110961175/191210988-8a50c70f-a3e2-4b18-9f80-7528f811e660.jpg)
![056f6232611d7e4fe9edf3ee4c5b1fbe](https://user-images.githubusercontent.com/110961175/191211001-90226117-fdd1-4c27-85a7-6f2ecf51c025.jpg)

**Comment by ApichayaUWU** [comment]
![Map_from_stranger_things](https://user-images.githubusercontent.com/110961569/191249629-07f8f8a0-d2e9-451c-aed8-c9eadab543d3.png)

**Comment by ApichayaUWU** [comment]
ปรับหน้าhomeอันล่าสุด
https://scratch.mit.edu/projects/734580709
