### ISSUE TITLE
4.7 ระบบรีโหลดกระสุน

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#17]

**Comment by Tiggers123** [comment]
https://scratch.mit.edu/projects/730509089/editor/

**Comment by Tiggers123** [comment]
https://scratch.mit.edu/projects/730509089

**Comment by Tiggers123** [comment]
https://scratch.mit.edu/projects/730509089 +แก้ไขช่วงระยะห่างของเวลาในการยิงกระสุน

**Comment by Tiggers123** [comment]
https://scratch.mit.edu/projects/730509089 อันนี้เสร็จจริงๆละ(แก้ไขช่วงกระสุนหมดให้ไม่สามารถยิงกระสุน)
