### ISSUE TITLE
ตัวอย่าวการรวมทุกอย่างเข้าด้วยกัน Alpha

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#19]

**Comment by TIT4nnnx** [comment]
https://scratch.mit.edu/projects/730500238

**Comment by TIT4nnnx** [comment]
อัพเดทเเล้ว  13/9/2565

**Comment by TIT4nnnx** [comment]
อัพเดท +ซอมบี้นักวิ่ง
เเละยิงZombie เเล้วกลายเป็นเด็ก

**Comment by TIT4nnnx** [comment]
ระบบเก็บ Hp ยังไม่ค่อยดีนะ

**Comment by TIT4nnnx** [comment]
อัพเดท 21:36     18/9/2565 +ซอมบี้ซูโม่ เเก้บัคนิดไหน่อย

**Comment by ApichayaUWU** [comment]
https://scratch.mit.edu/projects/733977939/
remixจากอันข้างบน

-เพิ่มUI หน้าhome หน้าleaderboard

**Comment by Waphyoo** [comment]
https://scratch.mit.edu/projects/734289404

**Comment by TIT4nnnx** [comment]
https://scratch.mit.edu/projects/734312017 Max
