### ISSUE TITLE
ตัวเกมฉบับ Alpha Test

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#22]
https://scratch.mit.edu/projects/734312017

**Comment by ApichayaUWU** [comment]
https://scratch.mit.edu/projects/734433757

เพิ่ม - ถ้าคนเล่นไม่ใส่ชื่อ/ว่างไว้ ชื่อที่ขึ้นบนleaderboardจะเป็น ???
<img width="410" alt="Untitled 3" src="https://user-images.githubusercontent.com/110961569/191286522-fd25518c-7e24-4d0d-844b-6a1a6a6bcbab.png">

**Comment by TIT4nnnx** [comment]
> https://scratch.mit.edu/projects/734433757
> 
> เพิ่ม - ถ้าคนเล่นไม่ใส่ชื่อ/ว่างไว้ ชื่อที่ขึ้นบนleaderboardจะเป็น ??? <img alt="Untitled 3" width="410" src="https://user-images.githubusercontent.com/110961569/191286522-fd25518c-7e24-4d0d-844b-6a1a6a6bcbab.png">

เค เดี๋ยวเพิ่มให้

**Comment by ApichayaUWU** [comment]
> > https://scratch.mit.edu/projects/734433757
> > เพิ่ม - ถ้าคนเล่นไม่ใส่ชื่อ/ว่างไว้ ชื่อที่ขึ้นบนleaderboardจะเป็น ??? <img alt="Untitled 3" width="410" src="https://user-images.githubusercontent.com/110961569/191286522-fd25518c-7e24-4d0d-844b-6a1a6a6bcbab.png">
> 
> เค เดี๋ยวเพิ่มให้

เอานี่ไปใส่ด้วย
![?](https://user-images.githubusercontent.com/110961569/191289274-ffa80ca8-6d92-4ade-8f68-abfec36272fb.png)

**Comment by TIT4nnnx** [comment]
![image](https://user-images.githubusercontent.com/104152299/191291346-cf40534b-1276-44d0-bff5-9bf162f3535f.png)

เรียบร้อยย
