### ISSUE TITLE
📌📌🌟🌟🌟🌟🌟🌟เอาเว้ยยยยยยยยยยยยย เกมเสร็จสักที 🌟🌟🌟🌟🌟🌟🌟📌📌

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#23]
📌 https://scratch.mit.edu/projects/734312017

**Comment by TIT4nnnx** [comment]
https://scratch.mit.edu/projects/734768050

**Comment by ApichayaUWU** [comment]
![What To Do-14](https://user-images.githubusercontent.com/110961569/191439494-7162df40-a2f8-4f47-b23f-4c8533d13126.jpg)
