### ISSUE TITLE
1 - หาเเนวเกมที่จะสร้าง

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#3]
ให้สมาชิกในกลุ่ม ส่งเเนวเกมที่คิดไว้ พร้อมกับตัวอย่างเเนวเกมนั้นๆ

**Comment by Tiggers123** [comment]
เอาแนวแบบยิงzombieดีไหม

**Comment by ApichayaUWU** [comment]
แนวrhythm game
https://store.steampowered.com/app/774171/Muse_Dash/

**Comment by TIT4nnnx** [comment]
เกมเหมือนมาริโอ้มั้ยย

**Comment by Waphyoo** [comment]
![ss12](https://user-images.githubusercontent.com/110945410/185073835-ce1c23be-35ad-43ef-be24-f58fd011b277.png)

**Comment by TIT4nnnx** [comment]
น่าสนมาก เเนวยิงซอมบี้

**Comment by Tiggers123** [comment]
> ![ss12](https://user-images.githubusercontent.com/110945410/185073835-ce1c23be-35ad-43ef-be24-f58fd011bแ
