### ISSUE TITLE
รายละเอียดของเกม เช่น การเก็บคะเเนน การหักคะเเนน การตัดสินผู้ชนะ วิธีการเล่น

### ISSUE THREAD

**Issue by TIT4nnnx** [TIT4nnnx/Game-Project-Groups-24-#7]

**Comment by TIT4nnnx** [comment]
ทุกคนนนน

**Comment by TIT4nnnx** [comment]
ทีมเกม จะเป็นฮาโลวีนนะ ชื่อเกม Candy saves zombies 📌📌📌📌📌📌📌📌📌📌📌📌📌
:ในเกม ตัวละครหลัก - ตัวละครหลักของเราจะมี HP ที่สามารถเพิ่มเเละลดได้ 
                               - ตัวละครจะมี HP อยู่3 point หากโดนเจ้า Zombie ถึวเนื้อถึงตัว HP ก็จะลดไป 1 Hit
                               - ในระหว่างเกม จะมีกระสูนปืน(ลูกอม) เเละ กล่องเพิ่ม HP Dropตามเเผนที่เกม 
                               - หากยิงลูกอมโดน Zombie เเล้ว จะได้เเต้ม ซึ้งจะเเสดงอยู่ทางด้านบนของหน้าจอเกม
                               - ผู้เล่นสามารถเล่นได้จนกว่า HP ของผู้เล่นจะหมด
                               - ตัวละครหลักจะมี Skill ต่างๆในการต่อสู้กับZombie ทุก Skill มีระยะเวลาในการรีคลูดาวน์
:ในเกม เจ้าZombie  - ซอมบี้จะมี 3 ประเภท เเต่ละประเภทจะมีความเร็ว ความทนทาน เเละขนาดของตัวซอมบี้ที่ต่างกันไป
                               - ซอมบี้เเต่ละประเภท ก็จะให้คะเเนนที่ต่างกันไปเช่นกัน
:สามารถเล่นได้สูงสุด 2 ผู้เล่น ช่วยกันเล่นเเละเก็บคะเเนนร่วมกันได้
:วิธีบังคับ เเละควบคุมการเล่น จะเป็นการบังคับการเคลื่อนที่ด้วยคีบอด เเละ บังคับการยิงกระสูนด้วยเมาส์

**Comment by TIT4nnnx** [comment]
@ApichayaUWU  ลงรูปทีมเกมไว้ในนี้ทีนะ

**Comment by ApichayaUWU** [comment]
![Title_Candy](https://user-images.githubusercontent.com/110961569/188717389-dbd2df28-92dd-4370-af5a-22dfa73f22e6.png)
![Ingame](https://user-images.githubusercontent.com/110961569/188717409-61e64947-9457-4498-ae91-197481d14cc4.png)
